config/routes.rb
BitfiServer::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root to: 'home#index'
  get '/accept' => 'home#accept'
  get '/login' => 'home#log_in'

  resources :users, only: :none do
    get :connected_devices, on: :member
    resources :connections, only: [:create, :index]
  end

  resources :connections, only: :none do
    post :activate, on: :member
  end

  match '*path' => redirect('http://54.210.58.4')
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :device
  belongs_to :tetherer, class_name: 'User'

  scope :active, -> { where(active: true) }
  scope :pending, -> { where(active: false, terminated_at: nil) }
  scope :expired, -> { where('terminated_at IS NOT NULL') }
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user
  has_many :connections
end

app/models/tetherer.rb
class Tetherer < ActiveRecord::Base
  attr_accessible :data_available, :mac_address
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :connections, foreign_key: 'tetherer_id'
  has_many :devices
  has_many :connected_devices, through: :connections, source: :device
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :redirect

  def redirect
    if request.host != '54.210.58.4'
      redirect_to "http://54.210.58.4"
      return
    end
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def create
    @device = Device.find_or_create_by_mac_address(params[:mac_address])
    @connection = Connection.new(
      tetherer_id: params[:user_id],
      device_id: @device.id,
      active: false
    )
    @connection.save!
    head :created
  end

  def index
    @tetherer = User.find(params[:user_id])
    respond_with @tetherer.connections.includes(:device).active
  end

  def activate
    @connection = Connection.find(params[:id])
    @connection.update_attributes!(active: true)
    redirect_to 'google.com'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, only: :index

  def index
    @tetherer = User.find_by_last_tether_ip(request.remote_ip)
    @connection = @tetherer.connections.pending.joins(:device)
      .where(devices: { user_id: current_user.id }).last
    if @connection.nil?
      @connection = @tetherer.connections.pending.joins(:device)
        .where('devices.user_id IS NULL').includes(:device).last
      @connection.device.user = current_user
      @connection.device.save!
    end
  end

  def log_in
    user = User.find_by_email(params[:email])
    if user and user.valid_password?(params[:password])
      user.update_attributes!(last_tether_ip: request.remote_ip)
      render status: 200, json: "Yes"
    else
      render status: 403, json: "No"
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    super
    print "IM HEREEEEEEEEEEEEEEEEEE"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  def connected_devices
    @user = User.find(params[:id])
    @macs = @user.connected_devices.map(&:mac_address)
    respond_with @macs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/accept.html.erb
<body>
	<div class="container">
	    <div class="block myBrand">
			<h1> Accept </h1>
			<h4> Email: <%= current_user.email %></h4>
			<h4> Balance: <%= current_user.balance %></h4>
			<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		</div>
    </div> <!-- /container -->
</body>

app/views/home/index.html.erb
<body>
  <div class="container">
    <div class="block myBrand">
      <h1>Welcome to Bitfi!</h1>
      <h4>Hi <%= current_user.email %>, click the button below for internet access.</h4>
      <div><%= link_to "Proceed", activate_connection_path(@connection), method: :post, class: "btn btn-lg btn-primary btn-block" %></div>
    </div>
  </div>
</body>

app/views/home/sorry.html.erb
<h1> Sorry </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BitfiServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>